### PR TITLE
apps/userdashboard/ModerationNotification/HoverButton: adding compone…

### PR DESCRIPTION
**Pull request by khamui**
…nt to handle hover text changes

squash

squash

### CODE REVIEW

**Comment by khamui** [comment]
okay will keep working on this one:
-[ ] issue with updating word after click
-[ ] `unhighlight` is not a word, alternatives?

**Comment by khamui** [comment]
@phillimorland indeed it didn't update after taking action (highlight, or blocked). That should be fixed now. Anyways there is a tiny little delay though. Had a hard time to find a solution, but couldn't manage to find one. Let me know if this is too annoying and I should try find a way to solve it or if I should make an issue and we go with this for now?

**Review by phillimorland — APPROVED** [review]
I think delay is fine, we can user test it if UX or PM's think it's an issue, nicely done! :)

**Comment by goapunk** [comment]
@phillimorland @khamui I'm a bit torn if we should handle it like this because it's rather working by accident, not by design. Maybe we can come up with a more robust solution? The problem here is that the `onMouseEnter` event isn't "reset" after clicking the button if you don't move the cursor away from it, so the hover effect is not triggered again. Showing the loading icon is basically a hack/trick to force that but looks rather ugly imo. One alternative for example could be to have a variable in the HoverButton which saves whether the cursor is on it, and set the text depending on the current value of that. This way we don't need to re-render the whole `notificationActionbar` but really just change the text of the button.

**Comment by phillimorland** [comment]
@khamui @goapunk ahh totally missed that, yes we should definitely make it as robust as possible! who wants to take that?

**Comment by khamui** [comment]
alright, thanks for the feedbsck guys! I am also not happy with the solution. will check how twitter solves it and mimic that

**Pull request merged**
