### PR TITLE
[#5764] apps/userdashboard: utilize moderator_marked field for highlight

### PR DESCRIPTION
**Pull request by sabinammm**
To test locally

- Get token using 

`curl -X POST http://localhost:8004/api/login/ -H 'Accept: application/json;' -d 'username=<username>&password=<password>'`
- Add token, project_pk and comment_pk to 

`curl -X PATCH http://localhost:8004/api/userdashboard/moderation/<project_pk>/comments/<comment_pk>/ -H 'Accept: application/json;' -H 'Authorization: Token <token>' -d 'is_moderator_marked=True'`

### CODE REVIEW

**Comment by Rineee** [comment]
Yes, that would be right! Buuut I just realized that this is not needed anymore.. I am super sorry for extra work, I copied that over from the old api and forgot to delete it. The old api was on the cĺassification model, so, that is why we needed to do this in order to change the comment model. But since this new api is on the comments directly, that is not needed anymore, the update just works automatically.. really sorry, should have deleted that before.
But we still need the part with the e-mail.. so: if you want, you could remove the whole part about updating the comment, and only check if 'is_blocked' is in request.data and if it is set to true send the e-mail.

**Review by Rineee — CHANGES_REQUESTED** [review]
Im sorry, that would work, but unfortunately not needed anymore..

**Comment by khamui** [comment]
@Rineee but its about the `Highlight` no? For this I think we do not have an Email, yet or do we?

Linking the frontend part:
https://github.com/liqd/a4-kosmo/pull/211#discussion_r861010730

**Comment by khamui** [comment]
Ah got it! makes sense

**Comment by fuzzylogic2000** [comment]
Sorry! I didn't notice and put you on the wrong (or unneeded) track there.

@Rineee should I do the blocked email-thingy along with the tests now?

**Pull request closed without merging**
