### PR TITLE
apps/notifications/email: base email adjustments

### PR DESCRIPTION
**Pull request by khamui**
@phillimorland its still wip. I was wondering how to change the logo? I think the kosmo logo is a fallback logo?

### CODE REVIEW

**Comment by phillimorland** [comment]
@khamui what do you mean by fallback? also did you try changing the file in the image folder? i think you'll need to do a make clean after and reinstall but it might work?! It's been a long while since I did email stuff

**Comment by khamui** [comment]
> @khamui what do you mean by fallback? also did you try changing the file in the image folder? i think you'll need to do a make clean after and reinstall but it might work?! It's been a long while since I did email stuff

probably nothing relevant with the fallback. it seems if there is no other logo "provided/uploaded" it will use the Kosmo. but maybe feature from aplus.

**Review by fuzzylogic2000 — COMMENTED** [review]
Is all of it specific to kosmo? Or are there bits that should be changed in a+ as well? In the second case doing the changes in a+ and rebasing will make things easier on the long run.

**Comment by khamui** [comment]
@fuzzylogic2000 okay I just talked to @mcastro-lqd and for now this email template adjustments only affect Kosmo. Aplus mails remain as they are.

**Review by phillimorland — APPROVED** [review]
very nice!

**Pull request merged**
