### PR TITLE
apps/notifications/blocked comment by moderator: adding template

### PR DESCRIPTION
**Pull request by khamui**
- [x] reason text (see taiga comment)
- [x] link to netiquette
- [x] link to discussion
- [x] Hello username,
- [x] project name (sub-heading)

### CODE REVIEW

**Comment by khamui** [comment]
the three unchecked items are still missing, but I could not find a way to make them work, maybe one of you has an idea. Feel free to alter this branch @fuzzylogic2000 @Rineee @sabinammm .

**Comment by khamui** [comment]
@fuzzylogic2000 Yeah. Thanks! just squashed

**Comment by fuzzylogic2000** [comment]
> @fuzzylogic2000 Yeah. Thanks! just squashed

@khamui Cool, thanks! But I still need to finish this PR... Will do so now.

**Comment by fuzzylogic2000** [comment]
@khamui @Rineee So, finally finished! When it is fine, we can merge?! (Or add the translations also in this PR?)

So, for the netiquette link: it takes the organisation's netiquette when there is one. Otherwise it uses the one set in wagtail for the whole page. And if there is none of these, it leaves out the whole sentence. (Rewrote the wording a tiny little bit for that, but also already let @rilanari know. :))

**Comment by khamui** [comment]
nice! thanks for making it. Merging and separating translations into another PR

**Pull request merged**
